//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmWebApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmWebApp.Form_Resource", typeof(Form_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment ID:.
        /// </summary>
        public static string F0101_Id {
            get {
                return ResourceManager.GetString("F0101_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date (တွေ့ဆုံလိုသည့်ရက်စွဲ)*:.
        /// </summary>
        public static string F0102_AppointmentDate {
            get {
                return ResourceManager.GetString("F0102_AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Number:.
        /// </summary>
        public static string F0103_QueNumber {
            get {
                return ResourceManager.GetString("F0103_QueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (အမည်)*:.
        /// </summary>
        public static string F0104_Name {
            get {
                return ResourceManager.GetString("F0104_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender (ကျား/မ)*:.
        /// </summary>
        public static string F0105_Gender {
            get {
                return ResourceManager.GetString("F0105_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth (မွေးသက္ကရာဇ်)*:.
        /// </summary>
        public static string F0106_DateOfBirth {
            get {
                return ResourceManager.GetString("F0106_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth (မွေးရပ်)*:.
        /// </summary>
        public static string F0107_PlaceOfBirth {
            get {
                return ResourceManager.GetString("F0107_PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality (နိုင်ငံသား):.
        /// </summary>
        public static string F0108_Nationality {
            get {
                return ResourceManager.GetString("F0108_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No (နိုင်ငံကူးလက်မှတ် #)*:.
        /// </summary>
        public static string F0109_PassportNumber {
            get {
                return ResourceManager.GetString("F0109_PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date (ထုတ်ပေးရက်စွဲ)*:.
        /// </summary>
        public static string F0110_PassportIssuedDate {
            get {
                return ResourceManager.GetString("F0110_PassportIssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Applied:.
        /// </summary>
        public static string F0111_ApplyCountryCode {
            get {
                return ResourceManager.GetString("F0111_ApplyCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sgp. IC / Permit No (စင်္ကာပူ  IC / ပါမစ် အမှတ်)*:.
        /// </summary>
        public static string F0112_ResidentStayPermitNo {
            get {
                return ResourceManager.GetString("F0112_ResidentStayPermitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC No (နိုင်ငံသားမှတ်ပုံတင်အမှတ်)*:.
        /// </summary>
        public static string F0113_NRIC_No {
            get {
                return ResourceManager.GetString("F0113_NRIC_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Address (စင်္ကာပူ နေရပ်လိပ်စာ)*:.
        /// </summary>
        public static string F0114_ContactAddr {
            get {
                return ResourceManager.GetString("F0114_ContactAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sgp. Address Line 2:.
        /// </summary>
        public static string F011402_ContactAddr {
            get {
                return ResourceManager.GetString("F011402_ContactAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email  (ဆက်သွယ်ရန်-အီးမေးလ်)*:.
        /// </summary>
        public static string F0115_ContactEmail {
            get {
                return ResourceManager.GetString("F0115_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone  (ဆက်သွယ်ရန်-ဖုန်း)*:.
        /// </summary>
        public static string F0116_ContactPhone {
            get {
                return ResourceManager.GetString("F0116_ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Address (မြန်မာ နေရပ်လိပ်စာ)*:.
        /// </summary>
        public static string F0117_HomeAddr {
            get {
                return ResourceManager.GetString("F0117_HomeAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Address Line 2:.
        /// </summary>
        public static string F011702_HomeAddr {
            get {
                return ResourceManager.GetString("F011702_HomeAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Phone (မြန်မာ ဖုန်း):.
        /// </summary>
        public static string F0118_HomePhone {
            get {
                return ResourceManager.GetString("F0118_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string F0119_Note {
            get {
                return ResourceManager.GetString("F0119_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Status:.
        /// </summary>
        public static string F0120_AppointmentStatus {
            get {
                return ResourceManager.GetString("F0120_AppointmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code:.
        /// </summary>
        public static string F0121_ActivationCode {
            get {
                return ResourceManager.GetString("F0121_ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type (အကြောင်းအရာ)*:.
        /// </summary>
        public static string F0122_AppointmentType {
            get {
                return ResourceManager.GetString("F0122_AppointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Employer Name (ကုမ္ပဏီ/အလုပ်ရှင်အမည်):.
        /// </summary>
        public static string F0123_CompanyName {
            get {
                return ResourceManager.GetString("F0123_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation (လုပ်ငန်း ရာထူးအမည်):.
        /// </summary>
        public static string F0124_Occupation {
            get {
                return ResourceManager.GetString("F0124_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stay Type (လက်ရှိ နေထိုင်ခွင့် အမျိုးအစား)*:.
        /// </summary>
        public static string F0125_StayType {
            get {
                return ResourceManager.GetString("F0125_StayType", resourceCulture);
            }
        }
    }
}
